version: "3"
services:
  elasticsearch:
    container_name: elasticsearch_service
    image: elasticsearch:6.4.2
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch/esdata/:/usr/share/elasticsearch/data/
      - ./elasticsearch/config/jvm.options:/usr/share/elasticsearch/config/jvm.options
  kibana:
    container_name: kibana_service
    image: kibana:6.4.2
    depends_on: ['elasticsearch']
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
  logstash:
    container_name: logstash_service
    image: logstash:6.8.3
    volumes: 
      - ./logstash/config/drives/:/usr/share/logstash/config/drives
      - ./logstash/config/jvm.options:/usr/share/logstash/config/jvm.options
      - ./logstash/config/users.conf:/usr/share/logstash/config/users.conf
    depends_on: ['elasticsearch']
