version: "3"
services:
  elasticsearch:
    container_name: elasticsearch_service
    image: elasticsearch:6.4.2
    ports:
      - "9200:9200"
  kibana:
    container_name: kibana_service
    image: kibana:6.4.2
    depends_on: ['elasticsearch']
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
  logstash:
    container_name: logstash_service
    image: logstash:6.8.3
    depends_on: ['elasticsearch']
